# If you appreciated my work <3 i appreciate that you would leave a tip in roblox by buying shirts thru my group (NOT OBLIGATORY, ITS TOTALLY DEPENDING ON U IF U FEEL TO DO IT)
roblox: https://www.roblox.com/communities/6085081/Groupe-De-Fond-Dinvestissement-Adouamien#!/about
